### ISSUE TITLE
master/examples/routing.rs  Compilation fails

### ISSUE THREAD

**Issue by dollarkillerx** [salvo-rs/salvo#24]
- https://github.com/salvo-rs/salvo/blob/master/examples/routing.rs

**dependencies**
```
rustc 1.51.0 (2fd73fabe 2021-03-23)
Deepin GNU/Linux 20.2

[dependencies]
salvo = { version = "0.11", features = ["full"] }
tokio = { version = "1", features = ["full"] }
```

**code**
```
use salvo::prelude::*;

#[tokio::main]
async fn main() {
    let debug_mode = true;
    let admin_mode = true;
    let router = Router::new()
        .get(index)
        .push(
            Router::new()
                .path("users")
                .before(auth)
                .post(create_user)
                .push(Router::new().path(r"<id:num>").post(update_user).delete(delete_user)),
        )
        .push(
            Router::new()
                .path("users")
                .get(list_users)
                .push(Router::new().path(r"<id:num>").get(show_user)),
        )
        .then(|router| {
            if debug_mode {
                router.push(Router::new().path("debug").get(debug))
            } else {
                router
            }
        })
        .then(|router| {
            if admin_mode {
                router.push(Router::new().path("admin").get(admin))
            } else {
                router
            }
        })
        ;

    Server::new(router).bind(([0, 0, 0, 0], 7878)).await;
}

#[fn_handler]
async fn admin(res: &mut Response) {
    res.render_plain_text("Admin page");
}
#[fn_handler]
async fn debug(res: &mut Response) {
    res.render_plain_text("Debug page");
}
#[fn_handler]
async fn index(res: &mut Response) {
    res.render_plain_text("Hello world!");
}
#[fn_handler]
async fn auth(res: &mut Response) {
    res.render_plain_text("user has authed\n\n");
}
#[fn_handler]
async fn list_users(res: &mut Response) {
    res.render_plain_text("list users");
}
#[fn_handler]
async fn show_user(res: &mut Response) {
    res.render_plain_text("show user");
}
#[fn_handler]
async fn create_user(res: &mut Response) {
    res.render_plain_text("user created");
}
#[fn_handler]
async fn update_user(res: &mut Response) {
    res.render_plain_text("user updated");
}
#[fn_handler]
async fn delete_user(res: &mut Response) {
    res.render_plain_text("user deleted");
}

```

**run** 
```
github@github:~/Workspace/demo1$ RUST_BACKTRACE=1 cargo run
warning: unused variable: `debug_mode`
 --> src/router.rs:7:9
  |
7 |     let debug_mode = true;
  |         ^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_debug_mode`
  |
  = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `admin_mode`
 --> src/router.rs:8:9
  |
8 |     let admin_mode = true;
  |         ^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_admin_mode`

warning: 2 warnings emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/demo1`
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/github/.cargo/registry/src/github.com-1ecc6299db9ec823/salvo_core-0.11.1/src/routing/filter/impls/path.rs:60:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::panicking::panic_bounds_check
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:69:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /home/github/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:182:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /home/github/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:15:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /home/github/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:2176:9
   6: <salvo_core::routing::filter::impls::path::CharPartBuilder<C> as salvo_core::routing::filter::impls::path::PartBuilder>::build
             at /home/github/.cargo/registry/src/github.com-1ecc6299db9ec823/salvo_core-0.11.1/src/routing/filter/impls/path.rs:60:18
   7: salvo_core::routing::filter::impls::path::PathParser::scan_parts
             at /home/github/.cargo/registry/src/github.com-1ecc6299db9ec823/salvo_core-0.11.1/src/routing/filter/impls/path.rs:486:40
   8: salvo_core::routing::filter::impls::path::PathParser::parse
             at /home/github/.cargo/registry/src/github.com-1ecc6299db9ec823/salvo_core-0.11.1/src/routing/filter/impls/path.rs:546:29
   9: salvo_core::routing::filter::impls::path::PathFilter::new
             at /home/github/.cargo/registry/src/github.com-1ecc6299db9ec823/salvo_core-0.11.1/src/routing/filter/impls/path.rs:589:32
  10: salvo_core::routing::router::Router::path
             at /home/github/.cargo/registry/src/github.com-1ecc6299db9ec823/salvo_core-0.11.1/src/routing/router.rs:152:21
  11: demo1::main::{{closure}}
             at ./src/main.rs:14:23
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/github/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/future/mod.rs:80:19
  13: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/github/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/park/thread.rs:263:54
  14: tokio::coop::with_budget::{{closure}}
             at /home/github/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/coop.rs:106:9
  15: std::thread::local::LocalKey<T>::try_with
             at /home/github/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:272:16
  16: std::thread::local::LocalKey<T>::with
             at /home/github/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:248:9
  17: tokio::coop::with_budget
             at /home/github/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/coop.rs:99:5
  18: tokio::coop::budget
             at /home/github/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/coop.rs:76:5
  19: tokio::park::thread::CachedParkThread::block_on
             at /home/github/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/park/thread.rs:263:31
  20: tokio::runtime::enter::Enter::block_on
             at /home/github/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/enter.rs:151:13
  21: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/github/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/thread_pool/mod.rs:71:9
  22: tokio::runtime::Runtime::block_on
             at /home/github/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/mod.rs:452:43
  23: demo1::main
             at ./src/main.rs:3:1
  24: core::ops::function::FnOnce::call_once
             at /home/github/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by driftluo** [comment]
Thank you for your report, this is a bug

**Comment by chrislearn** [comment]
@driftluo Thanks for your PR. 
@dollarkillerx You can use latest version 0.11.2.
