### ISSUE TITLE
IPv6 & IPv4 use same port crash.

### ISSUE THREAD

**Issue by dryBranch** [salvo-rs/salvo#591]
**Describe the bug**
use IPv6 `[::]` and IPv4 `0.0.0.0` and use same port(eg.`21000`) crash in my raspberry pi4.

**To Reproduce**
```rust
use salvo::prelude::*;

#[tokio::main]
async fn main() {
    let router = Router::with_path("<**path>").get(cached_proxy);
    tokio::spawn(async {
        let router = Router::with_path("<**path>").get(cached_proxy);
        let acceptor = TcpListener::new(String::from("[::]:21000")).bind().await; Server::new(acceptor).serve(router).await;
    });
    let acceptor = TcpListener::new(String::from("0.0.0.0:21000")).bind().await; Server::new(acceptor).serve(router).await;
}
#[handler]
async fn cached_proxy(_req: &mut Request, _res: &mut Response) { }
```

**Expected behavior**
support tcpv4 and tcpv6 at same time.

**Screenshots**
output
```bash
pi@raspbian:~/workspace/rust/cached_api$ cargo r -r
   Compiling cached_api v0.1.0 (/home/pi/workspace/rust/cached_api)
    Finished release [optimized] target(s) in 34.11s
     Running `target/release/cached_api`
thread 'tokio-runtime-worker' panicked at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/salvo_core-0.63.1/src/conn/mod.rs:201:31:
called `Result::unwrap()` on an `Err` value: Io(Os { code: 98, kind: AddrInUse, message: "Address already in use" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
^C
```

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser ...
 - Version salvo 0.61 & 0.63.1 rustc 1.73.

**additional**
It's OK in Windows 10.
It's OK use `[::1]` and `0.0.0.0` when using same port in raspberry pi4.
It's OK use `[::]` alone.

**Backtrace**
```bash
pi@raspbian:~/workspace/rust/cached_api$ RUST_BACKTRACE=full cargo r -r
    Finished release [optimized] target(s) in 0.73s
     Running `target/release/cached_api`
thread 'tokio-runtime-worker' panicked at /home/pi/.cargo/registry/src/github.com-1ecc6299db9ec823/salvo_core-0.63.1/src/conn/mod.rs:201:31:
called `Result::unwrap()` on an `Err` value: Io(Os { code: 98, kind: AddrInUse, message: "Address already in use" })
stack backtrace:
   0:     0xaaaae111a6ec - std::backtrace_rs::backtrace::libunwind::trace::heaab0e590535aeb3
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0xaaaae111a6ec - std::backtrace_rs::backtrace::trace_unsynchronized::h89cc7ae9ebb707d7
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0xaaaae111a6ec - std::sys_common::backtrace::_print_fmt::h08c31be18fedf422
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
   3:     0xaaaae111a6ec - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc38bcf44d9e857e3
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:44:22
   4:     0xaaaae113b27c - core::fmt::rt::Argument::fmt::ha5b752f9cd7ef4a3
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/rt.rs:138:9
   5:     0xaaaae113b27c - core::fmt::write::h9fac187ae7486f3c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/mod.rs:1094:21
   6:     0xaaaae11178dc - std::io::Write::write_fmt::h239e9fb6296b3a7f
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/io/mod.rs:1714:15
   7:     0xaaaae111a520 - std::sys_common::backtrace::_print::h52f67cfa8753b0ab
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:47:5
   8:     0xaaaae111a520 - std::sys_common::backtrace::print::hdea7481e2c957a93
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:34:9
   9:     0xaaaae111bba4 - std::panicking::default_hook::{{closure}}::h7c36fa733369c49e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:270:22
  10:     0xaaaae111b8cc - std::panicking::default_hook::h303eee75f9a8f6a8
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:290:9
  11:     0xaaaae111c168 - std::panicking::rust_panic_with_hook::h270c94381ec34744
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:707:13
  12:     0xaaaae111c030 - std::panicking::begin_panic_handler::{{closure}}::h3653e3502bcc1625
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:599:13
  13:     0xaaaae111abd0 - std::sys_common::backtrace::__rust_end_short_backtrace::h6b8510f2f024eeeb
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
  14:     0xaaaae111bd80 - rust_begin_unwind
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
  15:     0xaaaae0f2c680 - core::panicking::panic_fmt::ha96945d7a1b20293
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
  16:     0xaaaae0f2c968 - core::result::unwrap_failed::h52241e4ea1d20f58
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
  17:     0xaaaae0f52bf8 - salvo_core::conn::Listener::bind::{{closure}}::h89a49ff811a8e5e2
  18:     0xaaaae0f36388 - cached_api::main::{{closure}}::{{closure}}::h98b1ee5eea1fab85
  19:     0xaaaae0f34f14 - tokio::runtime::task::core::Core<T,S>::poll::hba8c5b3c48cf2b94
  20:     0xaaaae0f2f4f0 - tokio::runtime::task::harness::Harness<T,S>::poll::h46d47dc1c4f2fd1b
  21:     0xaaaae10d2668 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::ha220636d44fac3be
  22:     0xaaaae10d0030 - tokio::runtime::context::scoped::Scoped<T>::set::h1ce4a5bf264f0863
  23:     0xaaaae10d2320 - tokio::runtime::scheduler::multi_thread::worker::run::h5a57c31435d58fe0
  24:     0xaaaae10e3adc - tokio::runtime::task::core::Core<T,S>::poll::h871775fbbe59196e
  25:     0xaaaae10cb0cc - tokio::runtime::task::harness::Harness<T,S>::poll::hb3a873bee79e751c
  26:     0xaaaae10edaac - tokio::runtime::blocking::pool::Inner::run::h8403d5d4d76e7800
  27:     0xaaaae10e4760 - std::sys_common::backtrace::__rust_begin_short_backtrace::h94edcef3c32dab02
  28:     0xaaaae10e8448 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc940c9bdbc895459
  29:     0xaaaae111e970 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h01303c6de09f5469
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2007:9
  30:     0xaaaae111e970 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h4f39e7995f973f4c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/alloc/src/boxed.rs:2007:9
  31:     0xaaaae111e970 - std::sys::unix::thread::Thread::new::thread_start::h9f792bc0c268271e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys/unix/thread.rs:108:17
  32:     0xffff950307e4 - start_thread
  33:     0xffff94eb559c - <unknown>
  34:                0x0 - <unknown>
^C
```

**Comment by chrislearn** [comment]
Only reproduced on raspberry pi4? I don't have device to test.

**Comment by dryBranch** [comment]
I run it in another raspberry pi3b+ with lastest `raspbian` os & `ubuntu server` instead of 3rd os in pi4.
The result is same. I don't know if it's a common problem in arm64 platforms, but I have no more arm64 devices for testing it.

**Comment by dryBranch** [comment]
I check it with `tokio` & `std`, same result. Maybe it's a spec problem of raspberry pi.
